### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ehsan-Fouladi** [Ehsan-Fouladi/social-media#1]
Page Detail bug When the page scrolls navbar It gets stuck and doesn't stick to the bottom anymore  Direction component Widget Downloads and slug [link](https://github.com/Ehsan-Fouladi/social-media/tree/main/components/Widget)

**Comment by Noorani-MM** [comment]
Bug fixed with this [commit](https://github.com/Ehsan-Fouladi/social-media/commit/db1be0a0066ea1dceea9412f358d28def9d048a9)
